### ISSUE TITLE
target: Callable

### ISSUE THREAD

**Issue by rongdisun** [qwertyuiop6/mm131#6]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from aio_mm131 import Aio_mm
  File "/home/admin/github/spider/mm131/aio_mm131.py", line 2, in <module>
    from aiomultiprocess import Pool
  File "/home/admin/.local/lib/python3.5/site-packages/aiomultiprocess/__init__.py", line 11, in <module>
    from .core import Pool, Process, Worker, set_context
  File "/home/admin/.local/lib/python3.5/site-packages/aiomultiprocess/core.py", line 69
    target: Callable
                 ^
SyntaxError: invalid syntax``

-----------------------------
再云服务器上跑的，python3.5版本，有路过的大佬解释一下吧

**Comment by qwertyuiop6** [comment]
aiomultiprocess requires Python 3.6 or newer　
https://pypi.org/project/aiomultiprocess/
升级一下python版本 ,大兄弟
